#!/bin/sh
set -eu
case "$1" in
 remove|deconfigure)
    if [ -d /run/systemd/system ]; then deb-systemd-invoke stop server-manager-https-renew.timer server-manager-https-renew.service server-manager.service || true; fi
    ;;
esac
